
// Design System Tokens
// Generated by Design System Refinery

export const theme = {
  colors: {
    color-2: '#8e44ad', // used 8x
    white: '#ffffff', // used 4x
    color-3: '#ecf0f1', // used 2x
    color-4: '#34495e', // used 2x
    color-5: '#95a5a6', // used 2x
    color-6: 'rgba(0, 0, 0, 0.08)', // used 2x
  },
  spacing: {
    spacing-1: '8px', // 8px
    spacing-3: '18px', // 18px
    spacing-2: '2px', // 2px
    spacing-5: '12px', // 12px
    spacing-4: '24px', // 24px
    spacing-6: '15px', // 15px
  },
  typography: {
    fontSize-2: '14px',
    fontSize-1: '20px',
    fontWeight-1: '700',
    fontWeight-2: '600',
    lineHeight-1: '1.6',
  }
} as const

export type Theme = typeof theme

// Styled-components theme provider setup
declare module 'styled-components' {
  export interface DefaultTheme extends Theme {}
}
